name: CD

on:
  push:
    branches: [ 강지훈/main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jihoonkang

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 권한 부여
        run: chmod +x ./gradlew

      - name: application.yml 생성
        env:
          APP_YML: ${{ secrets.APPLICATION_YML }}
        run: |
          mkdir -p src/main/resources
          printf '%s' "$APP_YML" > src/main/resources/application.yml

      - name: Gradle 빌드
        run: ./gradlew build -x test

      - name: EC2 서버 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/7th-BE-Blog/jihoonkang

            echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
            echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml
            echo "${{ secrets.ENV_FILE }}" > .env

            git pull origin main

            ./gradlew build -x test

            docker compose down
            docker compose up --build -d

            docker compose ps
